package com.ycm.kata.datacollection.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ycm.kata.datacollection.model.entity.ProjectEntity;
import com.ycm.kata.datacollection.model.entity.LocationInfo;

import com.ycm.kata.datacollection.model.ProjectEntityDao;
import com.ycm.kata.datacollection.model.LocationInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig projectEntityDaoConfig;
    private final DaoConfig locationInfoDaoConfig;

    private final ProjectEntityDao projectEntityDao;
    private final LocationInfoDao locationInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        projectEntityDaoConfig = daoConfigMap.get(ProjectEntityDao.class).clone();
        projectEntityDaoConfig.initIdentityScope(type);

        locationInfoDaoConfig = daoConfigMap.get(LocationInfoDao.class).clone();
        locationInfoDaoConfig.initIdentityScope(type);

        projectEntityDao = new ProjectEntityDao(projectEntityDaoConfig, this);
        locationInfoDao = new LocationInfoDao(locationInfoDaoConfig, this);

        registerDao(ProjectEntity.class, projectEntityDao);
        registerDao(LocationInfo.class, locationInfoDao);
    }
    
    public void clear() {
        projectEntityDaoConfig.clearIdentityScope();
        locationInfoDaoConfig.clearIdentityScope();
    }

    public ProjectEntityDao getProjectEntityDao() {
        return projectEntityDao;
    }

    public LocationInfoDao getLocationInfoDao() {
        return locationInfoDao;
    }

}
