package com.ycm.kata.datacollection.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ycm.kata.datacollection.model.entity.ProjectEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig projectEntityDaoConfig;

    private final ProjectEntityDao projectEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        projectEntityDaoConfig = daoConfigMap.get(ProjectEntityDao.class).clone();
        projectEntityDaoConfig.initIdentityScope(type);

        projectEntityDao = new ProjectEntityDao(projectEntityDaoConfig, this);

        registerDao(ProjectEntity.class, projectEntityDao);
    }
    
    public void clear() {
        projectEntityDaoConfig.clearIdentityScope();
    }

    public ProjectEntityDao getProjectEntityDao() {
        return projectEntityDao;
    }

}
