/*   1:    */ package org.apache.poi.hssf.record.chart;
/*   2:    */ 
/*   3:    */ import org.apache.poi.hssf.record.RecordInputStream;
/*   4:    */ import org.apache.poi.hssf.record.StandardRecord;
/*   5:    */ import org.apache.poi.util.BitField;
/*   6:    */ import org.apache.poi.util.BitFieldFactory;
/*   7:    */ import org.apache.poi.util.HexDump;
/*   8:    */ import org.apache.poi.util.LittleEndianOutput;
/*   9:    */ 
/*  10:    */ public final class TextRecord
/*  11:    */   extends StandardRecord
/*  12:    */ {
/*  13:    */   public static final short sid = 4133;
/*  14: 33 */   private static final BitField dataLabelPlacement = BitFieldFactory.getInstance(15);
/*  15: 34 */   private static final BitField autoColor = BitFieldFactory.getInstance(1);
/*  16: 35 */   private static final BitField showKey = BitFieldFactory.getInstance(2);
/*  17: 36 */   private static final BitField showValue = BitFieldFactory.getInstance(4);
/*  18: 37 */   private static final BitField vertical = BitFieldFactory.getInstance(8);
/*  19: 38 */   private static final BitField autoGeneratedText = BitFieldFactory.getInstance(16);
/*  20: 39 */   private static final BitField generated = BitFieldFactory.getInstance(32);
/*  21: 40 */   private static final BitField autoLabelDeleted = BitFieldFactory.getInstance(64);
/*  22: 41 */   private static final BitField autoBackground = BitFieldFactory.getInstance(128);
/*  23: 42 */   private static final BitField rotation = BitFieldFactory.getInstance(1792);
/*  24: 44 */   private static final BitField showCategoryLabelAsPercentage = BitFieldFactory.getInstance(2048);
/*  25: 45 */   private static final BitField showValueAsPercentage = BitFieldFactory.getInstance(4096);
/*  26: 46 */   private static final BitField showBubbleSizes = BitFieldFactory.getInstance(8192);
/*  27: 47 */   private static final BitField showLabel = BitFieldFactory.getInstance(16384);
/*  28:    */   private byte field_1_horizontalAlignment;
/*  29:    */   public static final byte HORIZONTAL_ALIGNMENT_LEFT = 1;
/*  30:    */   public static final byte HORIZONTAL_ALIGNMENT_CENTER = 2;
/*  31:    */   public static final byte HORIZONTAL_ALIGNMENT_BOTTOM = 3;
/*  32:    */   public static final byte HORIZONTAL_ALIGNMENT_JUSTIFY = 4;
/*  33:    */   private byte field_2_verticalAlignment;
/*  34:    */   public static final byte VERTICAL_ALIGNMENT_TOP = 1;
/*  35:    */   public static final byte VERTICAL_ALIGNMENT_CENTER = 2;
/*  36:    */   public static final byte VERTICAL_ALIGNMENT_BOTTOM = 3;
/*  37:    */   public static final byte VERTICAL_ALIGNMENT_JUSTIFY = 4;
/*  38:    */   private short field_3_displayMode;
/*  39:    */   public static final short DISPLAY_MODE_TRANSPARENT = 1;
/*  40:    */   public static final short DISPLAY_MODE_OPAQUE = 2;
/*  41:    */   private int field_4_rgbColor;
/*  42:    */   private int field_5_x;
/*  43:    */   private int field_6_y;
/*  44:    */   private int field_7_width;
/*  45:    */   private int field_8_height;
/*  46:    */   private short field_9_options1;
/*  47:    */   public static final short ROTATION_NONE = 0;
/*  48:    */   public static final short ROTATION_TOP_TO_BOTTOM = 1;
/*  49:    */   public static final short ROTATION_ROTATED_90_DEGREES = 2;
/*  50:    */   public static final short ROTATION_ROTATED_90_DEGREES_CLOCKWISE = 3;
/*  51:    */   private short field_10_indexOfColorValue;
/*  52:    */   private short field_11_options2;
/*  53:    */   public static final short DATA_LABEL_PLACEMENT_CHART_DEPENDENT = 0;
/*  54:    */   public static final short DATA_LABEL_PLACEMENT_OUTSIDE = 1;
/*  55:    */   public static final short DATA_LABEL_PLACEMENT_INSIDE = 2;
/*  56:    */   public static final short DATA_LABEL_PLACEMENT_CENTER = 3;
/*  57:    */   public static final short DATA_LABEL_PLACEMENT_AXIS = 4;
/*  58:    */   public static final short DATA_LABEL_PLACEMENT_ABOVE = 5;
/*  59:    */   public static final short DATA_LABEL_PLACEMENT_BELOW = 6;
/*  60:    */   public static final short DATA_LABEL_PLACEMENT_LEFT = 7;
/*  61:    */   public static final short DATA_LABEL_PLACEMENT_RIGHT = 8;
/*  62:    */   public static final short DATA_LABEL_PLACEMENT_AUTO = 9;
/*  63:    */   public static final short DATA_LABEL_PLACEMENT_USER_MOVED = 10;
/*  64:    */   private short field_12_textRotation;
/*  65:    */   
/*  66:    */   public TextRecord() {}
/*  67:    */   
/*  68:    */   public TextRecord(RecordInputStream in)
/*  69:    */   {
/*  70: 96 */     this.field_1_horizontalAlignment = in.readByte();
/*  71: 97 */     this.field_2_verticalAlignment = in.readByte();
/*  72: 98 */     this.field_3_displayMode = in.readShort();
/*  73: 99 */     this.field_4_rgbColor = in.readInt();
/*  74:100 */     this.field_5_x = in.readInt();
/*  75:101 */     this.field_6_y = in.readInt();
/*  76:102 */     this.field_7_width = in.readInt();
/*  77:103 */     this.field_8_height = in.readInt();
/*  78:104 */     this.field_9_options1 = in.readShort();
/*  79:105 */     this.field_10_indexOfColorValue = in.readShort();
/*  80:106 */     this.field_11_options2 = in.readShort();
/*  81:107 */     this.field_12_textRotation = in.readShort();
/*  82:    */   }
/*  83:    */   
/*  84:    */   public String toString()
/*  85:    */   {
/*  86:112 */     StringBuffer buffer = new StringBuffer();
/*  87:    */     
/*  88:114 */     buffer.append("[TEXT]\n");
/*  89:115 */     buffer.append("    .horizontalAlignment  = ").append("0x").append(HexDump.toHex(getHorizontalAlignment())).append(" (").append(getHorizontalAlignment()).append(" )");
/*  90:    */     
/*  91:    */ 
/*  92:118 */     buffer.append(System.getProperty("line.separator"));
/*  93:119 */     buffer.append("    .verticalAlignment    = ").append("0x").append(HexDump.toHex(getVerticalAlignment())).append(" (").append(getVerticalAlignment()).append(" )");
/*  94:    */     
/*  95:    */ 
/*  96:122 */     buffer.append(System.getProperty("line.separator"));
/*  97:123 */     buffer.append("    .displayMode          = ").append("0x").append(HexDump.toHex(getDisplayMode())).append(" (").append(getDisplayMode()).append(" )");
/*  98:    */     
/*  99:    */ 
/* 100:126 */     buffer.append(System.getProperty("line.separator"));
/* 101:127 */     buffer.append("    .rgbColor             = ").append("0x").append(HexDump.toHex(getRgbColor())).append(" (").append(getRgbColor()).append(" )");
/* 102:    */     
/* 103:    */ 
/* 104:130 */     buffer.append(System.getProperty("line.separator"));
/* 105:131 */     buffer.append("    .x                    = ").append("0x").append(HexDump.toHex(getX())).append(" (").append(getX()).append(" )");
/* 106:    */     
/* 107:    */ 
/* 108:134 */     buffer.append(System.getProperty("line.separator"));
/* 109:135 */     buffer.append("    .y                    = ").append("0x").append(HexDump.toHex(getY())).append(" (").append(getY()).append(" )");
/* 110:    */     
/* 111:    */ 
/* 112:138 */     buffer.append(System.getProperty("line.separator"));
/* 113:139 */     buffer.append("    .width                = ").append("0x").append(HexDump.toHex(getWidth())).append(" (").append(getWidth()).append(" )");
/* 114:    */     
/* 115:    */ 
/* 116:142 */     buffer.append(System.getProperty("line.separator"));
/* 117:143 */     buffer.append("    .height               = ").append("0x").append(HexDump.toHex(getHeight())).append(" (").append(getHeight()).append(" )");
/* 118:    */     
/* 119:    */ 
/* 120:146 */     buffer.append(System.getProperty("line.separator"));
/* 121:147 */     buffer.append("    .options1             = ").append("0x").append(HexDump.toHex(getOptions1())).append(" (").append(getOptions1()).append(" )");
/* 122:    */     
/* 123:    */ 
/* 124:150 */     buffer.append(System.getProperty("line.separator"));
/* 125:151 */     buffer.append("         .autoColor                = ").append(isAutoColor()).append('\n');
/* 126:152 */     buffer.append("         .showKey                  = ").append(isShowKey()).append('\n');
/* 127:153 */     buffer.append("         .showValue                = ").append(isShowValue()).append('\n');
/* 128:154 */     buffer.append("         .vertical                 = ").append(isVertical()).append('\n');
/* 129:155 */     buffer.append("         .autoGeneratedText        = ").append(isAutoGeneratedText()).append('\n');
/* 130:156 */     buffer.append("         .generated                = ").append(isGenerated()).append('\n');
/* 131:157 */     buffer.append("         .autoLabelDeleted         = ").append(isAutoLabelDeleted()).append('\n');
/* 132:158 */     buffer.append("         .autoBackground           = ").append(isAutoBackground()).append('\n');
/* 133:159 */     buffer.append("         .rotation                 = ").append(getRotation()).append('\n');
/* 134:160 */     buffer.append("         .showCategoryLabelAsPercentage     = ").append(isShowCategoryLabelAsPercentage()).append('\n');
/* 135:161 */     buffer.append("         .showValueAsPercentage     = ").append(isShowValueAsPercentage()).append('\n');
/* 136:162 */     buffer.append("         .showBubbleSizes          = ").append(isShowBubbleSizes()).append('\n');
/* 137:163 */     buffer.append("         .showLabel                = ").append(isShowLabel()).append('\n');
/* 138:164 */     buffer.append("    .indexOfColorValue    = ").append("0x").append(HexDump.toHex(getIndexOfColorValue())).append(" (").append(getIndexOfColorValue()).append(" )");
/* 139:    */     
/* 140:    */ 
/* 141:167 */     buffer.append(System.getProperty("line.separator"));
/* 142:168 */     buffer.append("    .options2             = ").append("0x").append(HexDump.toHex(getOptions2())).append(" (").append(getOptions2()).append(" )");
/* 143:    */     
/* 144:    */ 
/* 145:171 */     buffer.append(System.getProperty("line.separator"));
/* 146:172 */     buffer.append("         .dataLabelPlacement       = ").append(getDataLabelPlacement()).append('\n');
/* 147:173 */     buffer.append("    .textRotation         = ").append("0x").append(HexDump.toHex(getTextRotation())).append(" (").append(getTextRotation()).append(" )");
/* 148:    */     
/* 149:    */ 
/* 150:176 */     buffer.append(System.getProperty("line.separator"));
/* 151:    */     
/* 152:178 */     buffer.append("[/TEXT]\n");
/* 153:179 */     return buffer.toString();
/* 154:    */   }
/* 155:    */   
/* 156:    */   public void serialize(LittleEndianOutput out)
/* 157:    */   {
/* 158:183 */     out.writeByte(this.field_1_horizontalAlignment);
/* 159:184 */     out.writeByte(this.field_2_verticalAlignment);
/* 160:185 */     out.writeShort(this.field_3_displayMode);
/* 161:186 */     out.writeInt(this.field_4_rgbColor);
/* 162:187 */     out.writeInt(this.field_5_x);
/* 163:188 */     out.writeInt(this.field_6_y);
/* 164:189 */     out.writeInt(this.field_7_width);
/* 165:190 */     out.writeInt(this.field_8_height);
/* 166:191 */     out.writeShort(this.field_9_options1);
/* 167:192 */     out.writeShort(this.field_10_indexOfColorValue);
/* 168:193 */     out.writeShort(this.field_11_options2);
/* 169:194 */     out.writeShort(this.field_12_textRotation);
/* 170:    */   }
/* 171:    */   
/* 172:    */   protected int getDataSize()
/* 173:    */   {
/* 174:198 */     return 32;
/* 175:    */   }
/* 176:    */   
/* 177:    */   public short getSid()
/* 178:    */   {
/* 179:203 */     return 4133;
/* 180:    */   }
/* 181:    */   
/* 182:    */   public Object clone()
/* 183:    */   {
/* 184:207 */     TextRecord rec = new TextRecord();
/* 185:    */     
/* 186:209 */     rec.field_1_horizontalAlignment = this.field_1_horizontalAlignment;
/* 187:210 */     rec.field_2_verticalAlignment = this.field_2_verticalAlignment;
/* 188:211 */     rec.field_3_displayMode = this.field_3_displayMode;
/* 189:212 */     rec.field_4_rgbColor = this.field_4_rgbColor;
/* 190:213 */     rec.field_5_x = this.field_5_x;
/* 191:214 */     rec.field_6_y = this.field_6_y;
/* 192:215 */     rec.field_7_width = this.field_7_width;
/* 193:216 */     rec.field_8_height = this.field_8_height;
/* 194:217 */     rec.field_9_options1 = this.field_9_options1;
/* 195:218 */     rec.field_10_indexOfColorValue = this.field_10_indexOfColorValue;
/* 196:219 */     rec.field_11_options2 = this.field_11_options2;
/* 197:220 */     rec.field_12_textRotation = this.field_12_textRotation;
/* 198:221 */     return rec;
/* 199:    */   }
/* 200:    */   
/* 201:    */   public byte getHorizontalAlignment()
/* 202:    */   {
/* 203:238 */     return this.field_1_horizontalAlignment;
/* 204:    */   }
/* 205:    */   
/* 206:    */   public void setHorizontalAlignment(byte field_1_horizontalAlignment)
/* 207:    */   {
/* 208:253 */     this.field_1_horizontalAlignment = field_1_horizontalAlignment;
/* 209:    */   }
/* 210:    */   
/* 211:    */   public byte getVerticalAlignment()
/* 212:    */   {
/* 213:267 */     return this.field_2_verticalAlignment;
/* 214:    */   }
/* 215:    */   
/* 216:    */   public void setVerticalAlignment(byte field_2_verticalAlignment)
/* 217:    */   {
/* 218:282 */     this.field_2_verticalAlignment = field_2_verticalAlignment;
/* 219:    */   }
/* 220:    */   
/* 221:    */   public short getDisplayMode()
/* 222:    */   {
/* 223:294 */     return this.field_3_displayMode;
/* 224:    */   }
/* 225:    */   
/* 226:    */   public void setDisplayMode(short field_3_displayMode)
/* 227:    */   {
/* 228:307 */     this.field_3_displayMode = field_3_displayMode;
/* 229:    */   }
/* 230:    */   
/* 231:    */   public int getRgbColor()
/* 232:    */   {
/* 233:315 */     return this.field_4_rgbColor;
/* 234:    */   }
/* 235:    */   
/* 236:    */   public void setRgbColor(int field_4_rgbColor)
/* 237:    */   {
/* 238:323 */     this.field_4_rgbColor = field_4_rgbColor;
/* 239:    */   }
/* 240:    */   
/* 241:    */   public int getX()
/* 242:    */   {
/* 243:331 */     return this.field_5_x;
/* 244:    */   }
/* 245:    */   
/* 246:    */   public void setX(int field_5_x)
/* 247:    */   {
/* 248:339 */     this.field_5_x = field_5_x;
/* 249:    */   }
/* 250:    */   
/* 251:    */   public int getY()
/* 252:    */   {
/* 253:347 */     return this.field_6_y;
/* 254:    */   }
/* 255:    */   
/* 256:    */   public void setY(int field_6_y)
/* 257:    */   {
/* 258:355 */     this.field_6_y = field_6_y;
/* 259:    */   }
/* 260:    */   
/* 261:    */   public int getWidth()
/* 262:    */   {
/* 263:363 */     return this.field_7_width;
/* 264:    */   }
/* 265:    */   
/* 266:    */   public void setWidth(int field_7_width)
/* 267:    */   {
/* 268:371 */     this.field_7_width = field_7_width;
/* 269:    */   }
/* 270:    */   
/* 271:    */   public int getHeight()
/* 272:    */   {
/* 273:379 */     return this.field_8_height;
/* 274:    */   }
/* 275:    */   
/* 276:    */   public void setHeight(int field_8_height)
/* 277:    */   {
/* 278:387 */     this.field_8_height = field_8_height;
/* 279:    */   }
/* 280:    */   
/* 281:    */   public short getOptions1()
/* 282:    */   {
/* 283:395 */     return this.field_9_options1;
/* 284:    */   }
/* 285:    */   
/* 286:    */   public void setOptions1(short field_9_options1)
/* 287:    */   {
/* 288:403 */     this.field_9_options1 = field_9_options1;
/* 289:    */   }
/* 290:    */   
/* 291:    */   public short getIndexOfColorValue()
/* 292:    */   {
/* 293:411 */     return this.field_10_indexOfColorValue;
/* 294:    */   }
/* 295:    */   
/* 296:    */   public void setIndexOfColorValue(short field_10_indexOfColorValue)
/* 297:    */   {
/* 298:419 */     this.field_10_indexOfColorValue = field_10_indexOfColorValue;
/* 299:    */   }
/* 300:    */   
/* 301:    */   public short getOptions2()
/* 302:    */   {
/* 303:427 */     return this.field_11_options2;
/* 304:    */   }
/* 305:    */   
/* 306:    */   public void setOptions2(short field_11_options2)
/* 307:    */   {
/* 308:435 */     this.field_11_options2 = field_11_options2;
/* 309:    */   }
/* 310:    */   
/* 311:    */   public short getTextRotation()
/* 312:    */   {
/* 313:443 */     return this.field_12_textRotation;
/* 314:    */   }
/* 315:    */   
/* 316:    */   public void setTextRotation(short field_12_textRotation)
/* 317:    */   {
/* 318:451 */     this.field_12_textRotation = field_12_textRotation;
/* 319:    */   }
/* 320:    */   
/* 321:    */   public void setAutoColor(boolean value)
/* 322:    */   {
/* 323:460 */     this.field_9_options1 = autoColor.setShortBoolean(this.field_9_options1, value);
/* 324:    */   }
/* 325:    */   
/* 326:    */   public boolean isAutoColor()
/* 327:    */   {
/* 328:469 */     return autoColor.isSet(this.field_9_options1);
/* 329:    */   }
/* 330:    */   
/* 331:    */   public void setShowKey(boolean value)
/* 332:    */   {
/* 333:478 */     this.field_9_options1 = showKey.setShortBoolean(this.field_9_options1, value);
/* 334:    */   }
/* 335:    */   
/* 336:    */   public boolean isShowKey()
/* 337:    */   {
/* 338:487 */     return showKey.isSet(this.field_9_options1);
/* 339:    */   }
/* 340:    */   
/* 341:    */   public void setShowValue(boolean value)
/* 342:    */   {
/* 343:496 */     this.field_9_options1 = showValue.setShortBoolean(this.field_9_options1, value);
/* 344:    */   }
/* 345:    */   
/* 346:    */   public boolean isShowValue()
/* 347:    */   {
/* 348:505 */     return showValue.isSet(this.field_9_options1);
/* 349:    */   }
/* 350:    */   
/* 351:    */   public void setVertical(boolean value)
/* 352:    */   {
/* 353:514 */     this.field_9_options1 = vertical.setShortBoolean(this.field_9_options1, value);
/* 354:    */   }
/* 355:    */   
/* 356:    */   public boolean isVertical()
/* 357:    */   {
/* 358:523 */     return vertical.isSet(this.field_9_options1);
/* 359:    */   }
/* 360:    */   
/* 361:    */   public void setAutoGeneratedText(boolean value)
/* 362:    */   {
/* 363:532 */     this.field_9_options1 = autoGeneratedText.setShortBoolean(this.field_9_options1, value);
/* 364:    */   }
/* 365:    */   
/* 366:    */   public boolean isAutoGeneratedText()
/* 367:    */   {
/* 368:541 */     return autoGeneratedText.isSet(this.field_9_options1);
/* 369:    */   }
/* 370:    */   
/* 371:    */   public void setGenerated(boolean value)
/* 372:    */   {
/* 373:550 */     this.field_9_options1 = generated.setShortBoolean(this.field_9_options1, value);
/* 374:    */   }
/* 375:    */   
/* 376:    */   public boolean isGenerated()
/* 377:    */   {
/* 378:559 */     return generated.isSet(this.field_9_options1);
/* 379:    */   }
/* 380:    */   
/* 381:    */   public void setAutoLabelDeleted(boolean value)
/* 382:    */   {
/* 383:568 */     this.field_9_options1 = autoLabelDeleted.setShortBoolean(this.field_9_options1, value);
/* 384:    */   }
/* 385:    */   
/* 386:    */   public boolean isAutoLabelDeleted()
/* 387:    */   {
/* 388:577 */     return autoLabelDeleted.isSet(this.field_9_options1);
/* 389:    */   }
/* 390:    */   
/* 391:    */   public void setAutoBackground(boolean value)
/* 392:    */   {
/* 393:586 */     this.field_9_options1 = autoBackground.setShortBoolean(this.field_9_options1, value);
/* 394:    */   }
/* 395:    */   
/* 396:    */   public boolean isAutoBackground()
/* 397:    */   {
/* 398:595 */     return autoBackground.isSet(this.field_9_options1);
/* 399:    */   }
/* 400:    */   
/* 401:    */   public void setRotation(short value)
/* 402:    */   {
/* 403:604 */     this.field_9_options1 = rotation.setShortValue(this.field_9_options1, value);
/* 404:    */   }
/* 405:    */   
/* 406:    */   public short getRotation()
/* 407:    */   {
/* 408:613 */     return rotation.getShortValue(this.field_9_options1);
/* 409:    */   }
/* 410:    */   
/* 411:    */   public void setShowCategoryLabelAsPercentage(boolean value)
/* 412:    */   {
/* 413:622 */     this.field_9_options1 = showCategoryLabelAsPercentage.setShortBoolean(this.field_9_options1, value);
/* 414:    */   }
/* 415:    */   
/* 416:    */   public boolean isShowCategoryLabelAsPercentage()
/* 417:    */   {
/* 418:631 */     return showCategoryLabelAsPercentage.isSet(this.field_9_options1);
/* 419:    */   }
/* 420:    */   
/* 421:    */   public void setShowValueAsPercentage(boolean value)
/* 422:    */   {
/* 423:640 */     this.field_9_options1 = showValueAsPercentage.setShortBoolean(this.field_9_options1, value);
/* 424:    */   }
/* 425:    */   
/* 426:    */   public boolean isShowValueAsPercentage()
/* 427:    */   {
/* 428:649 */     return showValueAsPercentage.isSet(this.field_9_options1);
/* 429:    */   }
/* 430:    */   
/* 431:    */   public void setShowBubbleSizes(boolean value)
/* 432:    */   {
/* 433:658 */     this.field_9_options1 = showBubbleSizes.setShortBoolean(this.field_9_options1, value);
/* 434:    */   }
/* 435:    */   
/* 436:    */   public boolean isShowBubbleSizes()
/* 437:    */   {
/* 438:667 */     return showBubbleSizes.isSet(this.field_9_options1);
/* 439:    */   }
/* 440:    */   
/* 441:    */   public void setShowLabel(boolean value)
/* 442:    */   {
/* 443:676 */     this.field_9_options1 = showLabel.setShortBoolean(this.field_9_options1, value);
/* 444:    */   }
/* 445:    */   
/* 446:    */   public boolean isShowLabel()
/* 447:    */   {
/* 448:685 */     return showLabel.isSet(this.field_9_options1);
/* 449:    */   }
/* 450:    */   
/* 451:    */   public void setDataLabelPlacement(short value)
/* 452:    */   {
/* 453:694 */     this.field_11_options2 = dataLabelPlacement.setShortValue(this.field_11_options2, value);
/* 454:    */   }
/* 455:    */   
/* 456:    */   public short getDataLabelPlacement()
/* 457:    */   {
/* 458:703 */     return dataLabelPlacement.getShortValue(this.field_11_options2);
/* 459:    */   }
/* 460:    */ }


/* Location:           F:\poi-3.17.jar
 * Qualified Name:     org.apache.poi.hssf.record.chart.TextRecord
 * JD-Core Version:    0.7.0.1
 */